### ISSUE TITLE
WP Activity Log still depends on wp_wsal_options

### ISSUE THREAD

**Issue by galapogos01** [WPWhiteSecurity/wp-activity-log#540]
Thanks for a great plugin!

I upgraded to from 4.1.2 to 4.1.3 and immediately began seeing these errors in the error log:

`
[Sat Aug 29 11:26:59.546108 2020] [proxy_fcgi:error] [pid 6070:tid x] [client x] AH01071: Got error 'PHP message: WordPress database error Table 'x.wp_wsal_options' doesn't exist for query SELECT * FROM wp_wsal_options WHERE option_name = 'wsal-version' made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WpSecurityAuditLog->init, WpSecurityAuditLog->GetOldVersion, WpSecurityAuditLog->GetGlobalOption, WSAL_Models_Option->GetOptionValue, WSAL_Adapters_MySQL_Option->GetNamedOption, WSAL_Adapters_MySQL_ActiveRecord->Load',`

It would appear the change to remove this table drops it on upgrade, but forgot the above dependency on this table.

Deactivating & reactivating the plugin recreated the table leaving it empty (but also removing the performance benefit of 1 less SQL query per pageload).

**Comment by martinkrcho** [comment]
@galapogos01, this has been resolved in version 4.1.4. Please update your plugin to get rid for the error message.
